"""Preset visual themes and styling templates for OBS Live Captions."""

from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass
class ThemePreset:
    id: str
    name: str
    description: str
    font_family: str
    font_size: str
    font_weight: str
    line_height: str
    text_color: str
    interim_color: str
    highlight_color: str
    background_box_color: str
    border_radius: str
    box_padding: str
    text_shadow: str
    text_stroke: str
    animation_style: str
    bottom_offset_px: int = 40
    box_layout: str = "banner"  # "banner", "pill", "boxless", "bar"
    accent_line: str = "none"  # "none", "top_divider", "bottom_divider", "left_marker"
    accent_color: str = "#38BDF8"
    category: str = "broadcast"  # "broadcast", "sanctuary", "cinema", "accessibility"


THEME_PRESETS: Dict[str, ThemePreset] = {
    "modern_clean": ThemePreset(
        id="modern_clean",
        name="Modern Glass",
        description="Translucent glassmorphism with crisp typography and subtle drop shadow.",
        font_family="Inter, sans-serif",
        font_size="32px",
        font_weight="700",
        line_height="1.35",
        text_color="#FFFFFF",
        interim_color="#90CAF9",
        highlight_color="#FFD166",
        background_box_color="rgba(15, 15, 20, 0.72)",
        border_radius="12px",
        box_padding="14px 26px",
        text_shadow="2px 2px 5px rgba(0, 0, 0, 0.95)",
        text_stroke="2px #000000",
        animation_style="word_pop",
        category="cinema",
    ),
    "broadcast_news": ThemePreset(
        id="broadcast_news",
        name="Broadcast Lower-Third",
        description="Network newsroom lower-third card with condensed headline font.",
        font_family="'Oswald', 'Inter', sans-serif",
        font_size="34px",
        font_weight="700",
        line_height="1.25",
        text_color="#FFFFFF",
        interim_color="#94A3B8",
        highlight_color="#38BDF8",
        background_box_color="rgba(10, 15, 28, 0.92)",
        border_radius="4px",
        box_padding="12px 24px",
        text_shadow="1px 1px 3px rgba(0, 0, 0, 0.8)",
        text_stroke="none",
        animation_style="instant",
        category="broadcast",
    ),
    "sanctuary_worship": ThemePreset(
        id="sanctuary_worship",
        name="Sanctuary & Worship",
        description="Warm gold typography with soft dark backing for worship services.",
        font_family="'Montserrat', sans-serif",
        font_size="36px",
        font_weight="600",
        line_height="1.4",
        text_color="#FFFBEB",
        interim_color="#FEF3C7",
        highlight_color="#F59E0B",
        background_box_color="rgba(20, 20, 26, 0.78)",
        border_radius="14px",
        box_padding="16px 30px",
        text_shadow="2px 2px 6px rgba(0, 0, 0, 0.9)",
        text_stroke="1.5px #0F0F12",
        animation_style="fade",
        category="sanctuary",
    ),
    "corporate_keynote": ThemePreset(
        id="corporate_keynote",
        name="Corporate Keynote",
        description="Clean executive aesthetic for webinars, conferences, and presentations.",
        font_family="'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        font_size="32px",
        font_weight="600",
        line_height="1.35",
        text_color="#F8FAFC",
        interim_color="#94A3B8",
        highlight_color="#60A5FA",
        background_box_color="rgba(24, 28, 36, 0.85)",
        border_radius="10px",
        box_padding="14px 26px",
        text_shadow="0 2px 8px rgba(0, 0, 0, 0.5)",
        text_stroke="none",
        animation_style="word_pop",
        category="cinema",
    ),
    "minimal_cinema": ThemePreset(
        id="minimal_cinema",
        name="Minimalist Cinema",
        description="Clean film subtitles with zero background box and deep drop shadows.",
        font_family="Roboto, sans-serif",
        font_size="34px",
        font_weight="700",
        line_height="1.3",
        text_color="#FFFFFF",
        interim_color="#E0E7FF",
        highlight_color="#FDE047",
        background_box_color="rgba(0, 0, 0, 0.0)",
        border_radius="0px",
        box_padding="0px",
        text_shadow="2px 2px 4px rgba(0, 0, 0, 1.0), 0 0 10px rgba(0, 0, 0, 0.8)",
        text_stroke="1.5px #000000",
        animation_style="fade",
        category="cinema",
    ),
    "stage_confidence": ThemePreset(
        id="stage_confidence",
        name="Stage Confidence Monitor",
        description="High-vis yellow typography on deep obsidian for 30-40ft stage reading.",
        font_family="'Inter', sans-serif",
        font_size="44px",
        font_weight="800",
        line_height="1.3",
        text_color="#FDE047",
        interim_color="#FEF08A",
        highlight_color="#FACC15",
        background_box_color="rgba(0, 0, 0, 0.95)",
        border_radius="8px",
        box_padding="18px 36px",
        text_shadow="none",
        text_stroke="none",
        animation_style="instant",
        category="sanctuary",
    ),
    "editorial_nordic": ThemePreset(
        id="editorial_nordic",
        name="Editorial Serif",
        description="Warm editorial serif typography for talk shows and podcasts.",
        font_family="'Lora', Georgia, serif",
        font_size="32px",
        font_weight="600",
        line_height="1.4",
        text_color="#FAFAF9",
        interim_color="#D6D3D1",
        highlight_color="#FBBF24",
        background_box_color="rgba(28, 25, 23, 0.82)",
        border_radius="10px",
        box_padding="14px 28px",
        text_shadow="1px 1px 4px rgba(0, 0, 0, 0.8)",
        text_stroke="1px #1C1917",
        animation_style="fade",
        category="cinema",
    ),
    "youtube_cc": ThemePreset(
        id="youtube_cc",
        name="Classic Broadcast CEA-708",
        description="Standardized high-contrast solid black badge subtitles.",
        font_family="'Open Sans', sans-serif",
        font_size="30px",
        font_weight="700",
        line_height="1.3",
        text_color="#FFFFFF",
        interim_color="#BBDEFB",
        highlight_color="#FFEE58",
        background_box_color="rgba(0, 0, 0, 0.92)",
        border_radius="4px",
        box_padding="8px 18px",
        text_shadow="none",
        text_stroke="none",
        animation_style="fade",
        category="broadcast",
    ),
    "opendyslexic": ThemePreset(
        id="opendyslexic",
        name="📖 OpenDyslexic (Accessibility)",
        description="Bottom-heavy letterforms engineered to enhance reading comfort & eliminate inversion.",
        font_family="'OpenDyslexic', sans-serif",
        font_size="32px",
        font_weight="700",
        line_height="1.5",
        text_color="#FFFFFF",
        interim_color="#7DD3FC",
        highlight_color="#FDE047",
        background_box_color="rgba(15, 23, 42, 0.88)",
        border_radius="12px",
        box_padding="16px 28px",
        text_shadow="2px 2px 4px rgba(0, 0, 0, 0.95)",
        text_stroke="2px #000000",
        animation_style="word_pop",
        category="accessibility",
    ),
    "broadcast_bar": ThemePreset(
        id="broadcast_bar",
        name="Flush Broadcast Bar",
        description="Edge-to-edge lower-third ticker with cyan divider rule, flush to bottom.",
        font_family="'Oswald', 'Inter', sans-serif",
        font_size="32px",
        font_weight="700",
        line_height="1.25",
        text_color="#FFFFFF",
        interim_color="#94A3B8",
        highlight_color="#38BDF8",
        background_box_color="rgba(10, 15, 26, 0.94)",
        border_radius="0px",
        box_padding="12px 32px",
        text_shadow="none",
        text_stroke="none",
        animation_style="instant",
        bottom_offset_px=0,
        box_layout="bar",
        accent_line="top_divider",
        accent_color="#38BDF8",
        category="broadcast",
    ),
    "sanctuary_high_contrast": ThemePreset(
        id="sanctuary_high_contrast",
        name="Sanctuary High-Contrast",
        description="Opaque black backing engineered against stage lighting washout on LED walls.",
        font_family="'Montserrat', sans-serif",
        font_size="36px",
        font_weight="700",
        line_height="1.4",
        text_color="#FFFFFF",
        interim_color="#FDE68A",
        highlight_color="#F59E0B",
        background_box_color="rgba(0, 0, 0, 0.92)",
        border_radius="8px",
        box_padding="16px 30px",
        text_shadow="none",
        text_stroke="none",
        animation_style="fade",
        bottom_offset_px=48,
        box_layout="banner",
        accent_line="none",
        accent_color="#F59E0B",
        category="sanctuary",
    ),
    "floating_clean": ThemePreset(
        id="floating_clean",
        name="Boxless Floating Subtitles",
        description="100% transparent backing with dual-stroke shadow. Clean view of video.",
        font_family="'Inter', sans-serif",
        font_size="34px",
        font_weight="700",
        line_height="1.3",
        text_color="#FFFFFF",
        interim_color="#BAE6FD",
        highlight_color="#FACC15",
        background_box_color="rgba(0, 0, 0, 0.0)",
        border_radius="0px",
        box_padding="0px",
        text_shadow="0 2px 8px rgba(0, 0, 0, 0.95), 0 0 16px rgba(0, 0, 0, 0.8)",
        text_stroke="2.5px #000000",
        animation_style="fade",
        bottom_offset_px=50,
        box_layout="boxless",
        accent_line="none",
        accent_color="#38BDF8",
        category="cinema",
    ),
    "chyron_left": ThemePreset(
        id="chyron_left",
        name="Off-Center Chyron Left",
        description="Left-docked lower-third leaving center stage clear for pastor & slides.",
        font_family="'Inter', sans-serif",
        font_size="30px",
        font_weight="700",
        line_height="1.35",
        text_color="#FFFFFF",
        interim_color="#94A3B8",
        highlight_color="#60A5FA",
        background_box_color="rgba(15, 23, 42, 0.90)",
        border_radius="10px",
        box_padding="14px 24px",
        text_shadow="1px 1px 3px rgba(0, 0, 0, 0.8)",
        text_stroke="none",
        animation_style="word_pop",
        bottom_offset_px=40,
        box_layout="pill",
        accent_line="left_marker",
        accent_color="#38BDF8",
        category="broadcast",
    ),
    "teleprompter_stage": ThemePreset(
        id="teleprompter_stage",
        name="Stage Teleprompter (40ft+)",
        description="Extra-large 44px yellow text engineered for long-distance stage reading.",
        font_family="'Inter', sans-serif",
        font_size="44px",
        font_weight="800",
        line_height="1.3",
        text_color="#FACC15",
        interim_color="#FEF08A",
        highlight_color="#FFFFFF",
        background_box_color="rgba(0, 0, 0, 0.95)",
        border_radius="10px",
        box_padding="20px 38px",
        text_shadow="none",
        text_stroke="none",
        animation_style="instant",
        bottom_offset_px=30,
        box_layout="banner",
        accent_line="none",
        accent_color="#FACC15",
        category="sanctuary",
    ),
}


def get_all_presets(custom_presets: Optional[Dict[str, dict]] = None) -> List[dict]:
    """Return all theme presets including built-in and user-saved custom presets."""
    from dataclasses import asdict
    presets = []
    for t in THEME_PRESETS.values():
        p_dict = asdict(t)
        p_dict["is_custom"] = False
        presets.append(p_dict)

    if custom_presets:
        for p_id, p_val in custom_presets.items():
            if isinstance(p_val, dict):
                p_entry = dict(p_val)
                p_entry["id"] = p_id
                p_entry["is_custom"] = True
                presets.append(p_entry)
    return presets
